# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug APK"
  lane :build_debug do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
  end

  desc "Build release APK"
  lane :build_release do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end

  desc "Submit a new Beta Build to Play Store Beta"
  lane :beta do
    gradle(
      task: "clean assembleRelease"
    )
    upload_to_play_store(
      track: 'beta',
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "clean assembleRelease"
    )
    upload_to_play_store
  end
end